import glob

_excluded_str = config.get("exclude", "")
EXCLUDED_JETS = [x.strip() for x in _excluded_str.split(",")] if _excluded_str else []

DATA_DIR = config.get("data-dir", "/eos/cms/store/group/phys_higgs/ttHcc/NanoAOD/NanoTuples/2024/mc/GluGluH-HTo2Tau_Par-M-125_TuneCP5_13p6TeV_powheg-pythia8/NanoTuples-uParTv3-parTlepID-NanoAODv15_RunIII2024Summer24MiniAODv6-150X_v2-v2/260608_185433/0000")
INPUT_FILES = glob.glob(f"{DATA_DIR}/*.root")
HADHAD = config.get("require-hadhad", "true")
PLOT_PARAMS = config.get("params", "X_mass/X_pt, X_eta")
PLOT_DIR = config.get("plot-dir", "/eos/user/m/mroine/www/")
NORMALIZE = config.get("normalize", "true");

_hadhad_string = "_hadhad" if HADHAD == "true" else ""
JET_FILES = {
    "AK4": f"jets/Jet{_hadhad_string}.root",
    "AK8": f"jets/fatJet{_hadhad_string}.root",
    "AK15": f"jets/AK15{_hadhad_string}.root"
}

REQUESTED_JETS = [j for j in JET_FILES.keys() if j not in EXCLUDED_JETS]

_ak4_str  = "Jet_"    if "AK4"  in REQUESTED_JETS else ""
_ak8_str  = "FatJet_" if "AK8"  in REQUESTED_JETS else ""
_ak15_str = "AK15_"   if "AK15" in REQUESTED_JETS else ""

_clean = (
    PLOT_PARAMS
    .replace("X", "")
    .replace("_", "")
    .replace(" ", "")
    .replace(",", "_")
    .replace("/", "over")

)

PLOT_PATH = f"{PLOT_DIR}{_ak4_str}{_ak8_str}{_ak15_str}{_clean}{_hadhad_string}_plot.png"

rule compile:
    input:
        "skimmer/BuildData.C"
    output:
        "skimmer/BuildData_C.so"
    shell:
        "root -l -b -q -e 'int status = gSystem->CompileMacro(\"skimmer/BuildData.C\", \"kf\"); gSystem->Exit(status == 1 ? 0 : 1);'"

rule all:
    input:
        PLOT_PATH

rule skim:
    input:
        [JET_FILES[j] for j in REQUESTED_JETS if j in JET_FILES],
        f"jets/RawEventInfo{_hadhad_string}.root"

rule skim_raw_data:
    input:
        INPUT_FILES,
        "skimmer/BuildData_C.so"
    output:
        f"jets/RawEventInfo{_hadhad_string}.root"
    params:
        pattern = f"{DATA_DIR}/*.root",
        hadhad = HADHAD
    shell:
        """
        root -l -b -q 'skimmer/BuildData.C+("{params.pattern}", false, false, false, true, {params.hadhad})'
        """

rule skim_ak4:
    input:
        INPUT_FILES,
        "skimmer/BuildData_C.so"
    output:
        f"jets/Jet{_hadhad_string}.root"
    params:
        pattern = f"{DATA_DIR}/*.root",
        hadhad = HADHAD
    shell:
        """
        root -l -b -q 'skimmer/BuildData.C+("{params.pattern}", true, false, false, false, {params.hadhad})'
        """

rule skim_ak8:
    input:
        INPUT_FILES,
        "skimmer/BuildData_C.so"
    output:
        f"jets/fatJet{_hadhad_string}.root"
    params:
        pattern = f"{DATA_DIR}/*.root",
        hadhad = HADHAD
    shell:
        """
        root -l -b -q 'skimmer/BuildData.C+("{params.pattern}", false, true, false, false, {params.hadhad})'
        """

rule skim_ak15:
    input:
        INPUT_FILES,
        "skimmer/BuildData_C.so"
    output:
        f"jets/AK15{_hadhad_string}.root"
    params:
        pattern = f"{DATA_DIR}/*.root",
        hadhad = HADHAD
    shell:
        """
        root -l -b -q 'skimmer/BuildData.C+("{params.pattern}", false, false, true, false, {params.hadhad})'
        """

rule plot:
    input:
        [JET_FILES[j] for j in REQUESTED_JETS if j in JET_FILES]
    output:
        PLOT_PATH
    params:
        ak4 = "true" if "AK4" in REQUESTED_JETS else "false",
        ak8 = "true" if "AK8" in REQUESTED_JETS else "false",
        ak15 = "true" if "AK15" in REQUESTED_JETS else "false",
        plot_params = PLOT_PARAMS,
        normalize = NORMALIZE,
        hadhad = HADHAD
    shell:
        """
        root -l -b -q 'plotter/Plots.C+({params.ak4}, {params.ak8}, {params.ak15}, "{params.plot_params}", "{output}", {params.normalize}, {params.hadhad})'
        """